{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kr328.gradle.golang",
    "module": "gradle-plugin",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-plugin-1.0.6.jar",
          "url": "gradle-plugin-1.0.6.jar",
          "size": 14988,
          "sha512": "6975910fbc3f86b5599d6311ccae4cd2814874505b275aad67739d8223839864b3368dad0041291d66e166f7150d1f3366d4df79484f3d492f2e9a0ddab909b9",
          "sha256": "0a53c2000806587fe563882c0fbeb20ce7461029b405e66cc6f326c3a7e86adf",
          "sha1": "eefb4281eb9f9ba30d85451176d44ce2278644b7",
          "md5": "cbcbf4377196c6a56fe1b1e287abdf4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-plugin-1.0.6.jar",
          "url": "gradle-plugin-1.0.6.jar",
          "size": 14988,
          "sha512": "6975910fbc3f86b5599d6311ccae4cd2814874505b275aad67739d8223839864b3368dad0041291d66e166f7150d1f3366d4df79484f3d492f2e9a0ddab909b9",
          "sha256": "0a53c2000806587fe563882c0fbeb20ce7461029b405e66cc6f326c3a7e86adf",
          "sha1": "eefb4281eb9f9ba30d85451176d44ce2278644b7",
          "md5": "cbcbf4377196c6a56fe1b1e287abdf4b"
        }
      ]
    }
  ]
}
